### ISSUE TITLE
instructions for use?

### ISSUE THREAD

**Issue by rachelss** [carpentries/undergrad-education-conversations#2]
Can some add instructions in the readme? Are we just using issues? submitting materials? any rules for issue formatting?

**Comment by biologyguy** [comment]
Working on it right now.

**Comment by tracykteal** [comment]
@biologyguy added a README with some information. https://github.com/carpentries/undergrad-education-conversations/

The idea is that people could add questions they have, things they want to discuss or curriculum or ideas that they want to share as issues, so we could continue conversations about computational training for undergrads. People are doing a lot of neat things, and it would be great to share what people are working on and how it's working.

@rachelss it was great to hear about what you're working on at Rhode Island. Would you be interested in creating an issue to give a bit of a description, and then potentially updating it as the course develops and is taught?
